services:
    web:
        container_name: website
        image: eriklandmark/lfs-website:beta
        ports:
            -   "3001:3000"
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        networks:
            - lfs-network

    watchtower:
        container_name: watchtower
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --debug --http-api-update
        environment:
            - WATCHTOWER_HTTP_API_TOKEN=
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        ports:
            - "9000:8080"
        networks:
            - lfs-network


networks:
    lfs-network:
        driver: bridge