services:
    web:
        image: lfs-website:beta
        container_name: lfs-website-beta
        build:
            context: .
            args:
                - VUE_APP_ENV=beta
        ports:
            -   "3001:3000"