services:
    web:
        image: lfs-website:release
        build:
            context: web
            args:
                - VUE_APP_ENV=release
        ports:
            - "3000:3000"
        depends_on:
            -   instagram-service
    instagram-service:
        build:
            context: instagram-service
        env_file: instagram-service/.env
        ports:
            - "3001:3000"
    google-service:
        build:
            context: google-service
        env_file: google-service/.env
        ports:
            - "3102:3001"