services:
    web:
        image: lfs-website:beta
        build: .
        ports:
            -   "3001:3000"

        environment:
            - VUE_APP_ENV=beta
    redeploy:
        container_name: redeploy
        image: redeploy:latest
        build: ./redeploy_service
        ports:
            -   "3002:3000"
        volumes:
            -   /var/run/docker.sock:/var/run/docker.sock