services:
    web:
        image: lfs-website:release
        build:
            context: web
            args:
                - VUE_APP_ENV=release
        ports:
            - "3000:3000"
    instagram-feed-service:
        build:
            context: instagram-service
        env_file: instagram-service/.env
        ports:
            - "3001:3000"