services:
    web:
        image: lfs-website:beta
        build:
            context: web
            args:
                - VUE_APP_ENV=beta
        ports:
            -   "3100:3000"
    instagram-feed-service:
        build:
            context: instagram-service
        env_file: instagram-service/.env
        ports:
            - "3101:3000"